services:
  jenkins:
    image: jenkins:jcasc
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      
    env_file: secrets.env
volumes:
  jenkins_home:
